In [39]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
dataset = pd.read_csv('data/train.csv')

In [3]:
dataset.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [4]:
y_train = dataset.iloc[:, -1].values
y_train

array([208500, 181500, 223500, ..., 266500, 142125, 147500])

In [5]:
X_train = dataset.iloc[:, 1:-1]
X_train.shape

(1460, 79)

In [6]:
X_train.isna().sum().loc[X_train.isna().sum() > 0]

LotFrontage      259
Alley           1369
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

### Dealing with missing values

In [7]:
X_train['LotFrontage'].head()

0    65.0
1    80.0
2    68.0
3    60.0
4    84.0
Name: LotFrontage, dtype: float64

In [8]:
X_train['LotFrontage'] = X_train['LotFrontage'].fillna(X_train['LotFrontage'].mean())

In [9]:
X_train.groupby('Alley').count()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Alley,,,,,,,,,,,,,,,,,,,,,
Grvl,50,50,50,50,50,50,50,50,50,50,...,50,50,0,14,4,50,50,50,50,50
Pave,41,41,41,41,41,41,41,41,41,41,...,41,41,0,4,0,41,41,41,41,41

In [10]:
X_train['Alley'].fillna('None', inplace=True)

In [11]:
print(X_train['MasVnrType'].head())
X_train.groupby('MasVnrType').count()

0    BrkFace
1       None
2    BrkFace
3       None
4    BrkFace
Name: MasVnrType, dtype: object

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
MasVnrType,,,,,,,,,,,,,,,,,,,,,
BrkCmn,15,15,15,15,15,15,15,15,15,15,...,15,15,0,7,2,15,15,15,15,15
BrkFace,445,445,445,445,445,445,445,445,445,445,...,445,445,2,80,11,445,445,445,445,445
None,864,864,864,864,864,864,864,864,864,864,...,864,864,4,188,40,864,864,864,864,864
Stone,128,128,128,128,128,128,128,128,128,128,...,128,128,1,6,1,128,128,128,128,128

In [12]:
X_train['MasVnrType'] = X_train['MasVnrType'].fillna('None')

In [13]:
X_train.groupby('MasVnrType').count()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
MasVnrType,,,,,,,,,,,,,,,,,,,,,
BrkCmn,15,15,15,15,15,15,15,15,15,15,...,15,15,0,7,2,15,15,15,15,15
BrkFace,445,445,445,445,445,445,445,445,445,445,...,445,445,2,80,11,445,445,445,445,445
None,872,872,872,872,872,872,872,872,872,872,...,872,872,4,188,40,872,872,872,872,872
Stone,128,128,128,128,128,128,128,128,128,128,...,128,128,1,6,1,128,128,128,128,128

In [14]:
X_train['MasVnrArea'].head()

0    196.0
1      0.0
2    162.0
3      0.0
4    350.0
Name: MasVnrArea, dtype: float64

In [15]:
X_train['MasVnrArea'].fillna(0, inplace=True)

In [16]:
X_train.loc[:, ['BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2']].head(20)

   BsmtQual BsmtCond BsmtExposure BsmtFinType1 BsmtFinType2
0        Gd       TA           No          GLQ          Unf
1        Gd       TA           Gd          ALQ          Unf
2        Gd       TA           Mn          GLQ          Unf
3        TA       Gd           No          ALQ          Unf
4        Gd       TA           Av          GLQ          Unf
5        Gd       TA           No          GLQ          Unf
6        Ex       TA           Av          GLQ          Unf
7        Gd       TA           Mn          ALQ          BLQ
8        TA       TA           No          Unf          Unf
9        TA       TA           No          GLQ          Unf
10       TA       TA           No          Rec          Unf
11       Ex       TA           No          GLQ          Unf
12       TA       TA           No          ALQ          Unf
13       Gd       TA           Av          Unf          Unf
14       TA       TA           No          BLQ          Unf
15       TA       TA           No          Unf          Unf
16       TA       TA           No          ALQ          Unf
17      NaN      NaN          NaN          NaN          NaN
18       TA       TA           No          GLQ          Unf
19       TA       TA           No          LwQ          Unf

In [17]:
X_train['BsmtQual'].fillna('None', inplace=True)
X_train['BsmtCond'].fillna('None', inplace=True)
X_train['BsmtExposure'].fillna('None', inplace=True)
X_train['BsmtFinType1'].fillna('None', inplace=True)
X_train['BsmtFinType2'].fillna('None', inplace=True)

In [18]:
X_train.shape

(1460, 79)

In [19]:
X_train = X_train.loc[X_train['Electrical'].isna() == False]
X_train.shape

(1459, 79)

In [20]:
X_train['FireplaceQu'].head(10)

0    NaN
1     TA
2     TA
3     Gd
4     TA
5    NaN
6     Gd
7     TA
8     TA
9     TA
Name: FireplaceQu, dtype: object

In [21]:
X_train['FireplaceQu'].fillna('None', inplace=True)

In [22]:
X_train.loc[:, ['GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond']].head() # 40

  GarageType  GarageYrBlt GarageFinish GarageQual GarageCond
0     Attchd       2003.0          RFn         TA         TA
1     Attchd       1976.0          RFn         TA         TA
2     Attchd       2001.0          RFn         TA         TA
3     Detchd       1998.0          Unf         TA         TA
4     Attchd       2000.0          RFn         TA         TA

In [23]:
X_train['GarageType'].fillna('None', inplace=True)
X_train['GarageYrBlt'].fillna('None', inplace=True)
X_train['GarageFinish'].fillna('None', inplace=True)
X_train['GarageQual'].fillna('None', inplace=True)
X_train['GarageCond'].fillna('None', inplace=True)

In [24]:
print(X_train.loc[:, ['PoolQC', 'Fence', 'MiscFeature']].head())
print(X_train['PoolQC'].unique())
print(X_train['Fence'].unique())
print(X_train['MiscFeature'].unique())

  PoolQC Fence MiscFeature
0    NaN   NaN         NaN
1    NaN   NaN         NaN
2    NaN   NaN         NaN
3    NaN   NaN         NaN
4    NaN   NaN         NaN
[nan 'Ex' 'Fa' 'Gd']
[nan 'MnPrv' 'GdWo' 'GdPrv' 'MnWw']
[nan 'Shed' 'Gar2' 'Othr' 'TenC']

In [25]:
X_train['PoolQC'].fillna('None', inplace=True)
X_train['Fence'].fillna('None', inplace=True)
X_train['MiscFeature'].fillna('None', inplace=True)

In [26]:
X_train.isna().sum().loc[X_train.isna().sum() > 0]

Series([], dtype: int64)

### Outliers!!!

### Feature Engineering!!

In [42]:
X_sc = MinMaxScaler()
transformed_npa = X_sc.fit_transform(X_train[list(X_train.describe().columns)])

In [43]:
X_train[list(X_train.describe().columns)].head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,60,65.000000,8450,7,5,2003,2003,196.0,706,0,...,548,0,61,0,0,0,2,0,2,2008
1,20,80.000000,9600,6,8,1976,1976,0.0,978,0,...,460,298,0,0,0,0,5,0,5,2007
2,60,68.000000,11250,7,5,2001,2002,162.0,486,0,...,608,0,42,0,0,0,9,0,9,2008
3,70,60.000000,9550,7,5,1915,1970,0.0,216,0,...,642,0,35,272,0,0,2,0,2,2006
4,60,84.000000,14260,8,5,2000,2000,350.0,655,0,...,836,192,84,0,0,0,12,0,12,2008
5,50,85.000000,14115,5,5,1993,1995,0.0,732,0,...,480,40,30,0,320,0,10,700,10,2009
6,20,75.000000,10084,8,5,2004,2005,186.0,1369,0,...,636,255,57,0,0,0,8,0,8,2007
7,60,70.049958,10382,7,6,1973,1973,240.0,859,32,...,484,235,204,228,0,0,11,350,11,2009
8,50,51.000000,6120,7,5,1931,1950,0.0,0,0,...,468,90,0,205,0,0,4,0,4,2008
9,190,50.000000,7420,5,6,1939,1950,0.0,851,0,...,205,0,4,0,0,0,1,0,1,2008
10,20,70.000000,11200,5,5,1965,1965,0.0,906,0,...,384,0,0,0,0,0,2,0,2,2008
11,60,85.000000,11924,9,5,2005,2006,286.0,998,0,...,736,147,21,0,0,0,7,0,7,2006
12,20,70.049958,12968,5,6,1962,1962,0.0,737,0,...,352,140,0,0,0,176,9,0,9,2008
13,20,91.000000,10652,7,5,2006,2007,306.0,0,0,...,840,160,33,0,0,0,8,0,8,2007
14,20,70.049958,10920,6,5,1960,1960,212.0,733,0,...,352,0,213,176,0,0,5,0,5,2008
15,45,51.000000,6120,7,8,1929,2001,0.0,0,0,...,576,48,112,0,0,0,7,0,7,2007
16,20,70.049958,11241,6,7,1970,1970,180.0,578,0,...,480,0,0,0,0,0,3,700,3,2010
17,90,72.000000,10791,4,5,1967,1967,0.0,0,0,...,516,0,0,0,0,0,10,500,10,2006
18,20,66.000000,13695,5,5,2004,2004,0.0,646,0,...,576,0,102,0,0,0,6,0,6,2008
19,20,70.000000,7560,5,6,1958,1965,0.0,504,0,...,294,0,0,0,0,0,5,0,5,2009

In [44]:
transformed_df = pd.DataFrame(transformed_npa)
transformed_df.columns = X_train.describe().columns
X_train[list(X_train.describe().columns)] = transformed_df
X_train[list(X_train.describe().columns)].head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,0.235294,RL,0.150685,0.033420,Pave,None,Reg,Lvl,AllPub,Inside,...,0.000000,0.090909,None,None,None,0.000000,0.090909,0.50,WD,Normal
1,0.000000,RL,0.202055,0.038795,Pave,None,Reg,Lvl,AllPub,FR2,...,0.000000,0.363636,None,None,None,0.000000,0.363636,0.25,WD,Normal
2,0.235294,RL,0.160959,0.046507,Pave,None,IR1,Lvl,AllPub,Inside,...,0.000000,0.727273,None,None,None,0.000000,0.727273,0.50,WD,Normal
3,0.294118,RL,0.133562,0.038561,Pave,None,IR1,Lvl,AllPub,Corner,...,0.000000,0.090909,None,None,None,0.000000,0.090909,0.00,WD,Abnorml
4,0.235294,RL,0.215753,0.060576,Pave,None,IR1,Lvl,AllPub,FR2,...,0.000000,1.000000,None,None,None,0.000000,1.000000,0.50,WD,Normal
5,0.176471,RL,0.219178,0.059899,Pave,None,IR1,Lvl,AllPub,Inside,...,0.000000,0.818182,None,MnPrv,Shed,0.045161,0.818182,0.75,WD,Normal
6,0.000000,RL,0.184932,0.041057,Pave,None,Reg,Lvl,AllPub,Inside,...,0.000000,0.636364,None,None,None,0.000000,0.636364,0.25,WD,Normal
7,0.235294,RL,0.167979,0.042450,Pave,None,IR1,Lvl,AllPub,Corner,...,0.000000,0.909091,None,None,Shed,0.022581,0.909091,0.75,WD,Normal
8,0.176471,RM,0.102740,0.022529,Pave,None,Reg,Lvl,AllPub,Inside,...,0.000000,0.272727,None,None,None,0.000000,0.272727,0.50,WD,Abnorml
9,1.000000,RL,0.099315,0.028605,Pave,None,Reg,Lvl,AllPub,Corner,...,0.000000,0.000000,None,None,None,0.000000,0.000000,0.50,WD,Normal
10,0.000000,RL,0.167808,0.046274,Pave,None,Reg,Lvl,AllPub,Inside,...,0.000000,0.090909,None,None,None,0.000000,0.090909,0.50,WD,Normal
11,0.235294,RL,0.219178,0.049658,Pave,None,IR1,Lvl,AllPub,Inside,...,0.000000,0.545455,None,None,None,0.000000,0.545455,0.00,New,Partial
12,0.000000,RL,0.167979,0.054537,Pave,None,IR2,Lvl,AllPub,Inside,...,0.366667,0.727273,None,None,None,0.000000,0.727273,0.50,WD,Normal
13,0.000000,RL,0.239726,0.043712,Pave,None,IR1,Lvl,AllPub,Inside,...,0.000000,0.636364,None,None,None,0.000000,0.636364,0.25,New,Partial
14,0.000000,RL,0.167979,0.044965,Pave,None,IR1,Lvl,AllPub,Corner,...,0.000000,0.363636,None,GdWo,None,0.000000,0.363636,0.50,WD,Normal
15,0.147059,RM,0.102740,0.022529,Pave,None,Reg,Lvl,AllPub,Corner,...,0.000000,0.545455,None,GdPrv,None,0.000000,0.545455,0.25,WD,Normal
16,0.000000,RL,0.167979,0.046465,Pave,None,IR1,Lvl,AllPub,CulDSac,...,0.000000,0.181818,None,None,Shed,0.045161,0.181818,1.00,WD,Normal
17,0.411765,RL,0.174658,0.044362,Pave,None,Reg,Lvl,AllPub,Inside,...,0.000000,0.818182,None,None,Shed,0.032258,0.818182,0.00,WD,Normal
18,0.000000,RL,0.154110,0.057935,Pave,None,Reg,Lvl,AllPub,Inside,...,0.000000,0.454545,None,None,None,0.000000,0.454545,0.50,WD,Normal
19,0.000000,RL,0.167808,0.029260,Pave,None,Reg,Lvl,AllPub,Inside,...,0.000000,0.363636,None,MnPrv,None,0.000000,0.363636,0.75,COD,Abnorml

In [ ]:
pd.get_dummies(X_train).shape

In [28]:
X_train.iloc[:, 70:].describe()

          PoolArea       MiscVal       MoSold       YrSold
count  1459.000000   1459.000000  1459.000000  1459.000000
mean      2.760795     43.518849     6.322824  2007.815627
std      40.191018    496.291826     2.704331     1.328542
min       0.000000      0.000000     1.000000  2006.000000
25%       0.000000      0.000000     5.000000  2007.000000
50%       0.000000      0.000000     6.000000  2008.000000
75%       0.000000      0.000000     8.000000  2009.000000
max     738.000000  15500.000000    12.000000  2010.000000

In [29]:
normalizers = {}
def normalize_column(X, column: str):
    df = X.loc[:, [column]]
    if column in normalizers.keys():
        normalizer = normalizers[column]
    else:
        normalizer = MinMaxScaler()
        normalizer.fit(df)
        normalizers[column] = normalizer
    np_scaled = normalizer.transform(df)
    X[column] = pd.DataFrame(np_scaled)[0]

for column in list(X_train.describe().columns):
    normalize_column(X_train, column)
X_train.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,0.235294,RL,0.150685,0.033420,Pave,None,Reg,Lvl,AllPub,Inside,...,0.0,0.0,None,None,None,0.0,0.090909,0.50,WD,Normal
1,0.000000,RL,0.202055,0.038795,Pave,None,Reg,Lvl,AllPub,FR2,...,0.0,0.0,None,None,None,0.0,0.363636,0.25,WD,Normal
2,0.235294,RL,0.160959,0.046507,Pave,None,IR1,Lvl,AllPub,Inside,...,0.0,0.0,None,None,None,0.0,0.727273,0.50,WD,Normal
3,0.294118,RL,0.133562,0.038561,Pave,None,IR1,Lvl,AllPub,Corner,...,0.0,0.0,None,None,None,0.0,0.090909,0.00,WD,Abnorml
4,0.235294,RL,0.215753,0.060576,Pave,None,IR1,Lvl,AllPub,FR2,...,0.0,0.0,None,None,None,0.0,1.000000,0.50,WD,Normal

In [30]:
normalizers

{'1stFlrSF': MinMaxScaler(copy=True, feature_range=(0, 1)),
 '2ndFlrSF': MinMaxScaler(copy=True, feature_range=(0, 1)),
 '3SsnPorch': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'BedroomAbvGr': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'BsmtFinSF1': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'BsmtFinSF2': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'BsmtFullBath': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'BsmtHalfBath': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'BsmtUnfSF': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'EnclosedPorch': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'Fireplaces': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'FullBath': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'GarageArea': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'GarageCars': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'GrLivArea': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'HalfBath': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'KitchenAbvGr': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'LotArea': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'LotFrontage': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'LowQualFinSF': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'MSSubClass': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'MasVnrArea': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'MiscVal': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'MoSold': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'OpenPorchSF': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'OverallCond': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'OverallQual': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'PoolArea': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'ScreenPorch': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'TotRmsAbvGrd': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'TotalBsmtSF': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'WoodDeckSF': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'YearBuilt': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'YearRemodAdd': MinMaxScaler(copy=True, feature_range=(0, 1)),
 'YrSold': MinMaxScaler(copy=True, feature_range=(0, 1))}

In [33]:
X_train_back.isna().sum().loc[X_train_back.isna().sum() > 0]

MSSubClass       1
LotFrontage      1
LotArea          1
OverallQual      1
OverallCond      1
YearBuilt        1
YearRemodAdd     1
MasVnrArea       1
BsmtFinSF1       1
BsmtFinSF2       1
BsmtUnfSF        1
TotalBsmtSF      1
1stFlrSF         1
2ndFlrSF         1
LowQualFinSF     1
GrLivArea        1
BsmtFullBath     1
BsmtHalfBath     1
FullBath         1
HalfBath         1
BedroomAbvGr     1
KitchenAbvGr     1
TotRmsAbvGrd     1
Fireplaces       1
GarageCars       1
GarageArea       1
WoodDeckSF       1
OpenPorchSF      1
EnclosedPorch    1
3SsnPorch        1
ScreenPorch      1
PoolArea         1
MiscVal          1
MoSold           1
YrSold           1
dtype: int64

In [55]:
df = X_train.loc[:, ['YrSold']]
min_max_scaler = MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(df)
X_train_back['YrSold'] = pd.DataFrame(np_scaled)[0]
X_train_back['YrSold'].head()

0    0.50
1    0.25
2    0.50
3    0.00
4    0.50
Name: YrSold, dtype: float64

In [47]:
col_npa = col.values

# normalizer = MinMaxScaler()
# normalizer.fit(col_npa)
# col_npa = normalizer.transform(col_npa)
print(col_npa.shape)
col_sr = pd.Series(col_npa)
print(col_npa[:10])
print(col_sr.head(10))

(1459,)
[2008 2007 2008 2006 2008 2009 2007 2009 2008 2008]
0    2008
1    2007
2    2008
3    2006
4    2008
5    2009
6    2007
7    2009
8    2008
9    2008
dtype: int64